config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'dashboard#dashboard'
  
  get 'dashboard' => 'dashboard#dashboard'
  get 'search' => 'dashboard#search'
  
  resources :customers do
    get 'search', on: :collection
  end
  resources :booked_rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booked_room.rb
class BookedRoom < ApplicationRecord
  default_scope { order(created_at: :desc) }
  
  belongs_to :room
  belongs_to :customer
  
  validates :start_date, :end_date, :status, presence: true
  validates :room_id, uniqueness: { scope: [:start_date, :end_date] }
  
  enum status: BOOKED_ROOM_STATUS_ENUM
  
  scope :get_booked_room_ids, -> () {
    BookedRoom.where(status: BOOKED_ROOM_STATUS_ENUM[0])
  }
end

app/models/customer.rb
class Customer < ApplicationRecord
  default_scope { order(:name) }
  
  has_many :booked_rooms, dependent: :destroy
  
  validates :name, :email, :phone_number, :address, presence: true
  validates :phone_number, length: { is: 10 }
  validates :email, uniqueness: true
  validates :phone_number, uniqueness: true
  
  scope :search_customers, -> (keyword) {
    where("lower(name) LIKE ?", "%#{keyword.downcase}%")
  }
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy

  validates :name, :address, :contact_number, presence: true
  validates :contact_number, length: { is: 10 }
  validates :contact_number, uniqueness: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel

  has_many :booked_rooms, dependent: :destroy
  
  validates :name, :room_type, :max_adults,  :max_children, :price, :amenities, presence: true
  validates :max_adults, :max_children, numericality: { only_integer: true }
  validates :max_adults, :price, numericality: { greater_than_or_equal_to: 1 }

  scope :get_available_rooms, -> () {
    Room.where('id NOT IN (?)', BookedRoom.get_booked_room_ids.pluck(:room_id))
  }

  scope :search_rooms, -> (keyword) {
    get_available_rooms.where("lower(name) LIKE ?", "%#{keyword.downcase}%")
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  
  validates :email, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/booked_rooms_controller.rb
class BookedRoomsController < ApplicationController
  def index
    @booked_rooms = BookedRoom.includes(:room, :customer).all
  end
  
  def new
    @booked_room = BookedRoom.new
  end
  
  def create
    @booked_room = BookedRoom.new(booked_room_params)
    
    if @booked_room.save
      redirect_to @booked_room
    else
      render 'new'
    end
  end
  
  def show
    @booked_room = BookedRoom.includes(:room, :customer).find(params[:id])
  end
  
  def edit
    @booked_room = BookedRoom.find(params[:id])
  end
  
  def update
    @booked_room = BookedRoom.find(params[:id])
    
    if @booked_room.update(booked_room_params)
      redirect_to @booked_room
    else
      render 'edit'
    end
  end
  
  def destroy
    @booked_room = BookedRoom.find(params[:id])
    @booked_room.destroy
    
    redirect_to booked_rooms_path
  end
  
  private
  def booked_room_params
    params.require(:booked_room).permit(:start_date, :end_date, :status, :check_in, :check_out, :room_id, :customer_id)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  
  def new
    @customer = Customer.new
  end
  
  def create
    @customer = Customer.new(customer_params)
    
    if @customer.save
      redirect_to @customer
    else
      render 'new'
    end
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render 'edit'
    end
  end
  
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    
    redirect_to customers_path
  end
  
  def search
    @search_keyword = search_params[:q]
    
    @customers = if @search_keyword
      Customer.search_customers(@search_keyword)
    else
      Customer.all
    end
    
    render 'customer_search'
  end
  
  private
  def customer_params
    params.require(:customer).permit(:name, :email, :phone_numer, :profile_pic, :address)
  end
  
  def search_params
    params.require(:customer).permit(:q)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard
    @available_rooms = Room.get_available_rooms
  end
  
  def search
    @search_keyword = params[:room][:q]

    @available_rooms = if @search_keyword
      Room.search_rooms(@search_keyword)
    else
      Room.get_available_rooms
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booked_rooms_helper.rb
module BookedRoomsHelper
  def get_rooms_options
    Room.all.collect { |room| [ room.name, room.id ] }
  end
  
  def get_customers_options
    Customer.all.collect { |customer| [ customer.name, customer.id ] }
  end
  
  def get_status_options
    BOOKED_ROOM_STATUS_ENUM.map { |status| [status.to_s.split('_').map(&:capitalize).join(' '), status] }
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/booked_rooms/_booked_room_form.html.erb
<div class="customer-form">
  <%= form_with model: @booked_room, local: true do |form| %>
  
  <% if @booked_room.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@booked_room.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @booked_room.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <p>
    <%= form.label :start_date %><br>
    <%= form.date_field :start_date %>
  </p>
  
  <p>
    <%= form.label :end_date %><br>
    <%= form.date_field :end_date %>
  </p>
  
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, get_status_options %>
  </p>
  
  <p>
    <%= form.label :check_in %><br>
    <%= form.time_field :check_in %>
  </p>
  
  <p>
    <%= form.label :check_out %><br>
    <%= form.time_field :check_out %>
  </p>
  
  <p>
    <%= form.label :room %><br>
    <%= form.select :room_id, get_rooms_options %>
  </p>
  
  <p>
    <%= form.label :customer %><br>
    <%= form.select :customer_id, get_customers_options %>
  </p>
  
  <p class="login-button customer-btn">
    <%= link_to 'Cancel', booked_rooms_path %> <%= form.submit "Save Booking" %>
  </p>
  
  <% end %>
</div>

app/views/booked_rooms/edit.html.erb
<div class="customer-details container">
  <h2>Edit Booking</h2>
  <p>Enter booking details below</p>
  <hr>
  
  <%= render 'booked_room_form' %>
</div>

app/views/booked_rooms/index.html.erb
<div class="container dashboard">
  <div class="row customer-padding">
    <div class="col-md-6">
      <h4>Listing Booked Rooms</h4>
    </div>
    <div class="col-md-6 padr0 customer-link">
      <%= link_to new_booked_room_path  do %>
      <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-plus-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
      </svg>
      Book Room
      <% end %>
    </div>
  </div>
  
  <table class="table table-hover">
    <tr>
      <th>Room</th>
      <th>Customer</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Check In</th>
      <th>Check Out</th>
      <th>Status</th>
      <th style="width: 5%" colspan="3">Actions</th>
    </tr>
    
    <% @booked_rooms.each do |booked_room| %>
    <tr>
      <td><%= booked_room.room.name %></td>
      <td><%= booked_room.customer.name %></td>
      <td><%= Date.strptime(booked_room.start_date.to_s, '%Y-%m-%d').strftime('%d/%m/%Y') %></td>
      <td><%= Date.strptime(booked_room.end_date.to_s, '%Y-%m-%d').strftime('%d/%m/%Y') %></td>
      <td><%= booked_room.check_in.strftime("%d/%m/%Y - %R %p") || "-" %></td>
      <td><%= booked_room.check_out.strftime("%d/%m/%Y - %R %p") || "-" %></td>
      <td><%= booked_room.status || "-" %></td>
      <td>
        <%= link_to booked_room_path(booked_room) do %>
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
          <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
        </svg>
        <% end %>
      </td>
      <td>
        <%= link_to edit_booked_room_path(booked_room) do %>
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
        </svg>
        <% end %>
      </td>
      <td>
        <%= link_to booked_room_path(booked_room), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
          <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/booked_rooms/new.html.erb
<div class="customer-details container">
  <h2>Create Booking</h2>
  <p>Enter booking details below</p>
  <hr>
  
  <%= render 'booked_room_form' %>
</div>

app/views/customers/_customer_form.html.erb
<div class="customer-form">
  <%= form_with model: @customer, local: true do |form| %>

    <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@customer.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>

    <p>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </p>

    <p>
      <%= form.label :phone_number %><br>
      <%= form.text_field :phone_number %>
    </p>

    <p>
      <%= form.label :profile_pic %><br>
      <%= form.text_field :profile_pic %>
    </p>

    <p>
      <%= form.label :address %><br>
      <%= form.text_area :address %>
    </p>

    <p class="login-button customer-btn">
      <%= link_to 'Cancel', customers_path %> <%= form.submit "Save Customer" %>
    </p>

  <% end %>
</div>

app/views/customers/_search_customer_form.html.erb
<div class="search-container">
	<%= form_with scope: :customer, url: '/customers/search', method: :get, local: true do |form| %>
	<div class="row">
		<div class="main-search col-md-10 pad-r0">
			<p>
				<%= form.text_field :q, value: keyword, placeholder: 'Search using customer name...', autocomplete: :off %>
			</p>
		</div>
		<div class="col-md-2 pad-l0 search-btn">
			<p>
				<%= form.submit "Find Customer" %>
			</p>
		</div>
	</div>
	<% end %>
</div>

app/views/customers/customer_search.html.erb
<div class="container dashboard">
  <h4 class="dashboard-welcome-note">Search Customers</h4>
  
  <%= render 'search_customer_form', keyword: @search_keyword %>
  
  <hr />
  
  <div class="row customer-padding">
    <div class="col-md-6">
      <h4>Matching Customers</h4>
    </div>
    <div class="col-md-6 padr0 customer-link">
      <%= link_to new_customer_path  do %>
      <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-plus-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
      </svg>
      Add Customer
      <% end %>
    </div>
  </div>
  
  <table class="table table-hover">
    <tr>
      <th style="width: 20%">Name</th>
      <th style="width: 20%">Email</th>
      <th>Phone Number</th>
      <th style="width: 30%">Address</th>
      <th style="width: 5%" colspan="3">Actions</th>
    </tr>
    
    <% if @customers.empty? %>
    <tr class="text-center">
      <td colspan="7">No match found</td>
    </tr>
    <% else %>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= customer.email %></td>
      <td><%= customer.phone_number %></td>
      <td><%= customer.address %></td>
      <td>
        <%= link_to customer_path(customer) do %>
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
          <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
        </svg>
        <% end %>
      </td>
      <td>
        <%= link_to edit_customer_path(customer) do %>
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
        </svg>
        <% end %>
      </td>
      <td>
        <%= link_to customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
          <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
        </svg>
        <% end %>
      </td>
    </tr>
    <% end %>
    <% end %>
  </table>
</div>

app/views/customers/edit.html.erb
<div class="customer-details container">
  <h2>Edit Customer</h2>
  <p>Enter your details below</p>
  <hr>
  
  <%= render 'customer_form' %>
</div>

app/views/customers/index.html.erb
<div class="container dashboard">
	<h4 class="dashboard-welcome-note">Search Customers</h4>

	<%= render 'search_customer_form', keyword: '' %>

  <hr />

  <div class="row customer-padding">
    <div class="col-md-6">
      <h4>Listing Customers</h4>
    </div>
    <div class="col-md-6 padr0 customer-link">
      <%= link_to new_customer_path  do %>
      <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-plus-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
      </svg>
      Add Customer
      <% end %>
    </div>
  </div>

  <table class="table table-hover">
    <tr>
      <th style="width: 20%">Name</th>
      <th style="width: 20%">Email</th>
      <th>Phone Number</th>
      <th style="width: 30%">Address</th>
      <th style="width: 5%" colspan="3">Actions</th>
    </tr>
    
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= customer.email %></td>
      <td><%= customer.phone_number %></td>
      <td><%= customer.address %></td>
      <td>
          <%= link_to customer_path(customer) do %>
            <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
              <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
            </svg>
          <% end %>
      </td>
      <td>
        <%= link_to edit_customer_path(customer) do %>
          <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
          </svg>
        <% end %>
      </td>
      <td>
        <%= link_to customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' } do %>
          <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
          </svg>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/customers/new.html.erb
<div class="customer-details container">
  <h2>Customer Form</h2>
  <p>Enter your details below</p>
  <hr>

  <%= render 'customer_form' %>
</div>

app/views/dashboard/_rooms_card.html.erb
<div class="card-container">
	<% @available_rooms.each do |available_room| %>
	<div class = "row cards">
		<div class="hotel-img col-md-3 pad0">
			<img src="https://cf.bstatic.com/xdata/images/hotel/square200/229986201.webp?k=dedff536e335c317ecded28d8d76462e87671be25c304501fe123a714757fedf&o=" alt="Hotel"> 
		</div>
		<div class="card-content col-md-9">
			<div class="room-header"><%= available_room.name %></div>
			<div><span class="content-header">Room Type: </span> <span><%= available_room.room_type %></span></div>
			<div><span class="content-header">Room Details: </span> <span><%= available_room.description %></span></div>
			<div><span class="content-header">Max Adults: </span> <span><%= available_room.max_adults %></span></div>
			<div><span class="content-header">Max Children: </span> <span><%= available_room.max_children %></span></div>
			<div><span class="content-header">Total Price: </span> <span class="price-details"><%= available_room.price %></span></div>
			<div><span class="content-header">Available Amenities: </span> <span><%= available_room.amenities %></span></div>
			<div class="book-btn" style="margin-top: 22px;"><a href="/booked_rooms/new" class="book-now">Book Now</a></div>
		</div>
	</div>
	<% end %>
</div>